{
 "title": "Logs Monitor",
 "description": "Monitor processed logs",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "level",
    "label": "Type",
    "query": {}
   },
   { "name": "search", "label": "Search" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Errors by Error Type",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(error) (count_over_time({level=\"$level\"} |= `$search` [$__range]))"
    }
   ]
  },
  {
   "title": "Total Errors by Error Type",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(error) (count_over_time({level=\"$level\"} |= `$search` [$__range]))"
    }
   ]
  },
  {
   "title": "Total Errors by Server Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum by(cb_version) (count_over_time({level=\"$level\"} |= `$search` [$__range]))"
    }
   ]
  },
  {
   "title": "Total Errors (On Prem / Capella)",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum by(capella) (count_over_time({level=\"$level\"} |= `$search` [$__range]))"
    }
   ]
  },
  {
   "title": "Plain Server Errors",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{level=\"$level\"} |= `$search`"
    }
   ]
  }
 ]
}