version: "2"
services:
  grafana:
    build:
      context: ./
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=info
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-storage:/var/lib/grafana'
volumes:
  grafana-storage: {}